### ISSUE TITLE
No module named ‘config.logging’

### ISSUE THREAD

**Issue by one00101** [prgumd/SpikeMS#3]
![09e450b145dd374e65158c20b92a1c7](https://user-images.githubusercontent.com/50857701/160060363-59414a90-f416-4309-947d-da1181e4e72e.png)

Whether the file named 'logging.py' is missing in the directory SpikeMS-main/config? When I run the command python test.py  --crop --maxBackgroundRatio=1.5  --segDatasetType="MOD" --modeltype="unetRNN6Layer_noBlock" --maskDir="Test/MOD/seq_room1_obj1/masks" --datafile="Test/MOD/seq_room1_obj1/room1obj1-001.hdf5" --checkpoint="pretrainedModels/EVIMO-pretrained/out/checkpoint.pth.tar",it has a ModuleNotFoundError：No module named ‘config.logging’.
![image](https://user-images.githubusercontent.com/50857701/160062051-772c003d-fcb8-4d41-9bf9-ab2906b4d442.png)

**Comment by chethanparameshwara** [comment]
Thanks for informing us. I just updated the file.
